CREATE DATABASE UNG_DUNG_QUAN_LY_QUAN_TRA_SUA
USE UNG_DUNG_QUAN_LY_QUAN_TRA_SUA
GO
USE master
GO
CREATE TABLE Size(
	Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	Ma VARCHAR(50) UNIQUE,
	TheTich NVARCHAR(50) DEFAULT NULL
)
GO 
CREATE TABLE DanhMuc(
	Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	Ma VARCHAR(50) UNIQUE,
	Ten NVARCHAR(50) DEFAULT null
)
GO
CREATE TABLE NguyenLieu(
	Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	Ma VARCHAR(50) UNIQUE,
	Ten NVARCHAR(50) DEFAULT NULL,
	Gia DECIMAL(20,0) DEFAULT 0,
	SoLuong INT,
	TrangThai INT,
	NXS DATE DEFAULT NULL,
	HXD int null,
	NhaCungCap NVARCHAR(50) DEFAULT NULL,
	XuatXu NVARCHAR(50) DEFAULT NULL
)

 CREATE TABLE SanPham (
	Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	Ma VARCHAR(50) UNIQUE,
	Ten NVARCHAR(100) DEFAULT NULL,
	DonGia DECIMAL(20,0) DEFAULT 0,
	TrangThai INT ,
	Vi NVARCHAR(50),
	Id_DM UNIQUEIDENTIFIER,
	Id_Size UNIQUEIDENTIFIER,
	Id_NL UNIQUEIDENTIFIER
 )
GO
CREATE TABLE Khachhang(
	Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	Ma VARCHAR(50) UNIQUE,
	HoTen NVARCHAR(100) DEFAULT NULL,
	GioiTinh NVARCHAR(50) DEFAULT NULL,
	DiaChi NVARCHAR(100) DEFAULT NULL,
	SDT VARCHAR(50) DEFAULT NULL,
	MoTa NVARCHAR(50) DEFAULT NULL
)
GO
CREATE TABLE ChucVu(
	Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	Ma VARCHAR(50) UNIQUE,
	Ten NVARCHAR(50) DEFAULT NULL
)
CREATE TABLE NhanVien(
	Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	Ma VARCHAR(50) UNIQUE,
	HoTen NVARCHAR(100) DEFAULT NULL,
	MatKhau VARCHAR(50) DEFAULT NULL,
	NgaySinh DATE ,
	GioiTinh NVARCHAR(50) DEFAULT NULL,
	DiaChi NVARCHAR(200) DEFAULT NULL,
	Email VARCHAR(50) DEFAULT NULL,
	SDT VARCHAR(50) DEFAULT NULL,
	Id_CV UNIQUEIDENTIFIER
)
CREATE TABLE KhuyenMai(
	Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	Ma VARCHAR(50) UNIQUE,
	DieuKien NVARCHAR(50) DEFAULT NULL
)
CREATE TABLE HoaDon (
	Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	Id_NV UNIQUEIDENTIFIER,
	Ma VARCHAR(50) UNIQUE,
	ngayTao DATE,
	TongTien DECIMAL(20,0),
	id_KH UNIQUEIDENTIFIER,
	TrangThai INT
)
CREATE TABLE KhuyenMaiChiTiet(
	Id_HD UNIQUEIDENTIFIER,
	Id_KM UNIQUEIDENTIFIER,
	SoTienGiam DECIMAL(20,0),
	ngayBD DATE,
	ngayKT DATE,
	CONSTRAINT PK_KhuyenMaiCHiTiet PRIMARY KEY(Id_HD, Id_KM),
	CONSTRAINT Fk1_KHCT FOREIGN KEY (Id_HD) REFERENCES HoaDon(Id),
	CONSTRAINT Fk2_KHCT FOREIGN KEY (Id_KM) REFERENCES KhuyenMai(Id)
)
CREATE TABLE HoaDonChiTiet(
	id_HD UNIQUEIDENTIFIER,
	id_SP UNIQUEIDENTIFIER,
	SL_Mua INT,
	DonGia DECIMAL(20,0)
	CONSTRAINT PK_HoaDonCT PRIMARY KEY(id_HD, id_SP),
	CONSTRAINT FK1_HDCT FOREIGN KEY(id_HD) REFERENCES HoaDon(Id),
	CONSTRAINT FK2_HDCT FOREIGN KEY(id_SP) REFERENCES SanPham(Id)
)
ALTER TABLE dbo.SanPham ADD CONSTRAINT FK1_sanPham FOREIGN KEY(Id_DM) REFERENCES dbo.DanhMuc(Id)
ALTER TABLE dbo.SanPham ADD CONSTRAINT FK2_sanPham FOREIGN KEY(Id_Size) REFERENCES dbo.Size(Id)
ALTER TABLE dbo.SanPham ADD CONSTRAINT FK3_sanPham FOREIGN KEY(Id_NL) REFERENCES dbo.NguyenLieu(Id)
ALTER TABLE dbo.HoaDon ADD CONSTRAINT Fk1_HD FOREIGN KEY(id_KH) REFERENCES dbo.Khachhang(Id)
ALTER TABLE dbo.HoaDon ADD CONSTRAINT Fk2_HD FOREIGN KEY(Id_NV) REFERENCES dbo.NhanVien(Id)
ALTER TABLE dbo.NhanVien ADD CONSTRAINT Fk1_NV FOREIGN KEY(Id_CV) REFERENCES dbo.ChucVu(Id)
-- insert
INSERT INTO dbo.ChucVu
(
    Id,
    Ma,
    Ten
)
VALUES
(   NEWID(), 'CV1',N'Nhân Viên'),
(   NEWID(), 'CV2',N'Quản Lý')
SELECT * FROM dbo.ChucVu
delete from ChucVu
INSERT INTO dbo.NhanVien
(
    Id,
    Ma,
    HoTen,
    MatKhau,
    NgaySinh,
    GioiTinh,
    DiaChi,
    Email,
    SDT,
    Id_CV
)
VALUES
(   NEWID(),'NV1',N'Nguyễn Văn Mạnh','manh123','2003-03-25',N'Nam', N'Thanh Hóa','','0364585263','8D4E1DC0-927F-4C3E-9652-6909C82FB761'),
(   NEWID(),'NV2',N'Nguyễn Văn Mạnh 2','manh123456','2003-03-25',N'Nữ', N'Thọ Xuân','','0364585265','5D0EB0DD-1D08-4AEE-AACD-94D6E0ED6A2D')
SELECT Id,Ma,HoTen,MatKhau,NgaySinh,GioiTinh,DiaChi,Email,SDT,Id_CV FROM dbo.NhanVien
insert into NguyenLieu values
(newid(), N'NL01',N'VŨ',1,1,1,'2003-07-29',12,N'Nga Hải',N'Nga Hải')

select * from NguyenLieu
